name: NausicaMedia
favicon: null
layout_spectrum: 0.7552
typography_spectrum: 0.99653
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: NausicaMedia sur The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#9c9c9c'
    - '#4262ab'
    - '#1d1d1b'
    - '#d9d9d9'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
