color:
  saturation: 0.8568061
  brandStrength: 0.6487519
  rhythmicContrast: 0.7940148
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.428585
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.7401434
typography_spectrum: 0.6188258
name: NausicaMedia
